name: Repack and Release

on:
  # 手动触发工作流
  workflow_dispatch:
  # 定时触发工作流 - 每天的12点（UTC +0）自动构建（CST 20:00）
  schedule:
    - cron: "0 12 * * *"

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  # BEEESSS_Hikari_Female
  repack-BHF:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout current repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Clone external repository
      - name: Clone external repository
        run: |
          git clone https://gitgud.io/Frostberg/degrees-of-lewdity-plus.git
          cd degrees-of-lewdity-plus

      # Step 3: Locate imagepacks and prepare img folder
      - name: Prepare img folder
        run: |
          cd degrees-of-lewdity-plus/imagepacks
          mkdir -p BEEESSS_Hikari_Female/img/                   #创建文件夹
          # cp -r -f vanilla/* BEEESSS_Hikari_Female/img/       #原版图包
          # cp -r -f dolp/* BEEESSS_Hikari_Female/img/          #DOLP图包
          cp -r -f b3s/* BEEESSS_Hikari_Female/img/
          cp -r -f kaervek/* BEEESSS_Hikari_Female/img/
          # cp -r -f dolp_b3s/* BEEESSS_Hikari_Female/img/      #DOLP美化图包
          cp -r -f b3s_hikfem/* BEEESSS_Hikari_Female/img/
          cp -r -f b3s_hikfemsubs/* BEEESSS_Hikari_Female/img/
          mv BEEESSS_Hikari_Female ../../BEEESSS_Hikari_Female  #移动回仓库默认路径下

      # Step 4: Set version and name
      - name: Set version
        id: version_step
        run: |
          echo "MOD_VERSION_BHF=$(date +'%y-%m-%d')" >> $GITHUB_ENV  # 设置版本号
          echo "MOD_NAME_BHF=BEEESSS_Hikari_Female" >> $GITHUB_ENV   # 设置模组名称

      # Step 5: Run Python script to package the folder
      - name: Run Python packaging script
        run: |
          cd BEEESSS_Hikari_Female
          python3 ../python/Art_Mods_Actions.py --input img --output ${{ env.MOD_NAME_BHF }}.zip --version ${{ env.MOD_VERSION_BHF }}
          mv BEEESSS_Hikari_Female.zip ../BEEESSS_Hikari_Female.zip
        env:
          MOD_NAME: ${{ env.MOD_NAME_BHF }}        # 传递 MOD_NAME 环境变量
          MOD_VERSION: ${{ env.MOD_VERSION_BHF }}  # 传递 MOD_VERSION 环境变量

      # Step 6: Upload artifact from workflow repack_BHF
      - name: Upload artifact from workflow repack_BHF
        uses: actions/upload-artifact@v4
        with:
          name: BEEESSS_Hikari_Female-package
          path: BEEESSS_Hikari_Female.zip

  # BEEESSS_Paril_Hairstyle_Extended
  repack-BPHE:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout current repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Clone external repository
      - name: Clone external repository
        run: |
          git clone https://gitgud.io/Frostberg/degrees-of-lewdity-plus.git
          cd degrees-of-lewdity-plus

      # Step 3: Locate imagepacks and prepare img folder
      - name: Prepare img folder
        run: |
          cd degrees-of-lewdity-plus/imagepacks
          mkdir -p BEEESSS_Paril_Hairstyle_Extended/img/                              #创建文件夹
          # cp -r -f vanilla/* BEEESSS_Paril_Hairstyle_Extended/img/                  #原版图包
          # cp -r -f dolp/* BEEESSS_Paril_Hairstyle_Extended/img/                     #DOLP图包
          cp -r -f b3s/* BEEESSS_Paril_Hairstyle_Extended/img/
          cp -r -f kaervek/* BEEESSS_Paril_Hairstyle_Extended/img/
          # cp -r -f dolp_b3s/* BEEESSS_Paril_Hairstyle_Extended/img/                 #DOLP美化图包
          cp -r -f parilold/* BEEESSS_Paril_Hairstyle_Extended/img/
          cp -r -f hairext/* BEEESSS_Paril_Hairstyle_Extended/img/  
          mv BEEESSS_Paril_Hairstyle_Extended ../../BEEESSS_Paril_Hairstyle_Extended  #移动回仓库默认路径下

      # Step 4: Set version and name
      - name: Set version
        id: version_step
        run: |
          echo "MOD_VERSION_BPHE=$(date +'%y-%m-%d')" >> $GITHUB_ENV            # 设置版本号
          echo "MOD_NAME_BPHE=BEEESSS_Paril_Hairstyle_Extended" >> $GITHUB_ENV  # 设置模组名称

      # Step 5: Run Python script to package the folder
      - name: Run Python packaging script
        run: |
          cd BEEESSS_Paril_Hairstyle_Extended
          python3 ../python/Art_Mods_Actions.py --input img --output ${{ env.MOD_NAME_BPHE }}.zip --version ${{ env.MOD_VERSION_BPHE }}
          mv BEEESSS_Paril_Hairstyle_Extended.zip ../BEEESSS_Paril_Hairstyle_Extended.zip
        env:
          MOD_NAME: ${{ env.MOD_NAME_BPHE }}        # 传递 MOD_NAME 环境变量
          MOD_VERSION: ${{ env.MOD_VERSION_BPHE }}  # 传递 MOD_VERSION 环境变量

      # Step 6: Upload artifact from workflow repack_BPHE
      - name: Upload artifact from workflow repack_BPHE
        uses: actions/upload-artifact@v4
        with:
          name: BEEESSS_Paril_Hairstyle_Extended-package
          path: BEEESSS_Paril_Hairstyle_Extended.zip

  # BEEESSS_Wax
  repack-BW:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout current repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Clone external repository
      - name: Clone external repository
        run: |
          git clone https://gitgud.io/Frostberg/degrees-of-lewdity-plus.git
          cd degrees-of-lewdity-plus

      # Step 3: Locate imagepacks and prepare img folder
      - name: Prepare img folder
        run: |
          cd degrees-of-lewdity-plus/imagepacks
          mkdir -p BEEESSS_Wax/img/                              #创建文件夹
          # cp -r -f vanilla/* BEEESSS_Wax/img/                  #原版图包
          # cp -r -f dolp/* BEEESSS_Wax/img/                     #DOLP图包
          cp -r -f b3s/* BEEESSS_Wax/img/
          cp -r -f kaervek/* BEEESSS_Wax/img/
          # cp -r -f dolp_b3s/* BEEESSS_Wax/img/                 #DOLP美化图包
          cp -r -f b3s_wax/* BEEESSS_Wax/img/
          mv BEEESSS_Wax ../../BEEESSS_Wax                       #移动回仓库默认路径下

      # Step 4: Set version and name
      - name: Set version
        id: version_step
        run: |
          echo "MOD_VERSION_BW=$(date +'%y-%m-%d')" >> $GITHUB_ENV            # 设置版本号
          echo "MOD_NAME_BW=BEEESSS_Wax" >> $GITHUB_ENV  # 设置模组名称

      # Step 5: Run Python script to package the folder
      - name: Run Python packaging script
        run: |
          cd BEEESSS_Wax
          python3 ../python/Art_Mods_Actions.py --input img --output ${{ env.MOD_NAME_BW }}.zip --version ${{ env.MOD_VERSION_BW }}
          mv BEEESSS_Wax.zip ../BEEESSS_Wax.zip
        env:
          MOD_NAME: ${{ env.MOD_NAME_BW }}        # 传递 MOD_NAME 环境变量
          MOD_VERSION: ${{ env.MOD_VERSION_BW }}  # 传递 MOD_VERSION 环境变量

      # Step 6: Upload artifact from workflow repack_BW
      - name: Upload artifact from workflow repack_BW
        uses: actions/upload-artifact@v4
        with:
          name: BEEESSS_Wax-package
          path: BEEESSS_Wax.zip

  # Goose_Female
  repack-GF:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout current repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Clone external repository
      - name: Clone external repository
        run: |
          git clone https://gitgud.io/Frostberg/degrees-of-lewdity-plus.git
          cd degrees-of-lewdity-plus

      # Step 3: Locate imagepacks and prepare img folder
      - name: Prepare img folder
        run: |
          cd degrees-of-lewdity-plus/imagepacks
          mkdir -p Goose_Female/img/                   #创建文件夹
          # cp -r -f vanilla/* Goose_Female/img/       #原版图包
          # cp -r -f dolp/* Goose_Female/img/          #DOLP图包
          cp -r -f goosefem/* Goose_Female/img/
          cp -r -f goosefemsubs/* Goose_Female/img/
          mv Goose_Female ../../Goose_Female  #移动回仓库默认路径下

      # Step 4: Set version and name
      - name: Set version
        id: version_step
        run: |
          echo "MOD_VERSION_GF=$(date +'%y-%m-%d')" >> $GITHUB_ENV  # 设置版本号
          echo "MOD_NAME_GF=Goose_Female" >> $GITHUB_ENV   # 设置模组名称

      # Step 5: Run Python script to package the folder
      - name: Run Python packaging script
        run: |
          cd Goose_Female
          python3 ../python/Art_Mods_Actions.py --input img --output ${{ env.MOD_NAME_GF }}.zip --version ${{ env.MOD_VERSION_GF }}
          mv Goose_Female.zip ../Goose_Female.zip
        env:
          MOD_NAME: ${{ env.MOD_NAME_GF }}        # 传递 MOD_NAME 环境变量
          MOD_VERSION: ${{ env.MOD_VERSION_GF }}  # 传递 MOD_VERSION 环境变量

      # Step 6: Upload artifact from workflow repack_GF
      - name: Upload artifact from workflow repack_GF
        uses: actions/upload-artifact@v4
        with:
          name: Goose_Female-package
          path: Goose_Female.zip

  # Goose_Female_Mysterious
  repack-GFM:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout current repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Clone external repository
      - name: Clone external repository
        run: |
          git clone https://gitgud.io/Frostberg/degrees-of-lewdity-plus.git
          cd degrees-of-lewdity-plus

      # Step 3: Locate imagepacks and prepare img folder
      - name: Prepare img folder
        run: |
          cd degrees-of-lewdity-plus/imagepacks
          mkdir -p Goose_Female_Mysterious/img/                     #创建文件夹
          # cp -r -f vanilla/* Goose_Female_Mysterious/img/         #原版图包
          # cp -r -f dolp/* Goose_Female_Mysterious/img/            #DOLP图包
          cp -r -f goosefem/* Goose_Female_Mysterious/img/
          cp -r -f goosefemsubs/* Goose_Female_Mysterious/img/
          cp -r -f mysterious/* Goose_Female_Mysterious/img/
          mv Goose_Female_Mysterious ../../Goose_Female_Mysterious  #移动回仓库默认路径下

      # Step 4: Set version and name
      - name: Set version
        id: version_step
        run: |
          echo "MOD_VERSION_GFM=$(date +'%y-%m-%d')" >> $GITHUB_ENV  # 设置版本号
          echo "MOD_NAME_GFM=Goose_Female_Mysterious" >> $GITHUB_ENV   # 设置模组名称

      # Step 5: Run Python script to package the folder
      - name: Run Python packaging script
        run: |
          cd Goose_Female_Mysterious
          python3 ../python/Art_Mods_Actions.py --input img --output ${{ env.MOD_NAME_GFM }}.zip --version ${{ env.MOD_VERSION_GFM }}
          mv Goose_Female_Mysterious.zip ../Goose_Female_Mysterious.zip
        env:
          MOD_NAME: ${{ env.MOD_NAME_GFM }}        # 传递 MOD_NAME 环境变量
          MOD_VERSION: ${{ env.MOD_VERSION_GFM }}  # 传递 MOD_VERSION 环境变量

      # Step 6: Upload artifact from workflow repack_GFM
      - name: Upload artifact from workflow repack_GFM
        uses: actions/upload-artifact@v4
        with:
          name: Goose_Female_Mysterious-package
          path: Goose_Female_Mysterious.zip

  create-release:
    runs-on: ubuntu-latest
    needs: [repack-BHF, repack-BPHE, repack-BW, repack-GF, repack-GFM]  # 完成依赖后开始

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 添加日期变量
      - name: Set release date
        run: echo "RELEASE_DATE=$(date +'%y-%m-%d')" >> $GITHUB_ENV

      # 下载工件
      - name: Download BEEESSS_Hikari_Female
        uses: actions/download-artifact@v4
        with:
          name: BEEESSS_Hikari_Female-package
          
      - name: Download BEEESSS_Paril_Hairstyle_Extended
        uses: actions/download-artifact@v4
        with:
          name: BEEESSS_Paril_Hairstyle_Extended-package

      - name: Download BEEESSS_Wax
        uses: actions/download-artifact@v4
        with:
          name: BEEESSS_Wax-package

      - name: Download Goose_Female
        uses: actions/download-artifact@v4
        with:
          name: Goose_Female-package

      - name: Download Goose_Female_Mysterious
        uses: actions/download-artifact@v4
        with:
          name: Goose_Female_Mysterious-package

      # 生成SHA256
      - name: Calculate SHA256 for BEEESSS_Hikari_Female.zip
        id: sha256-BHF
        run: |
            sha256=$(shasum -a 256 BEEESSS_Hikari_Female.zip | awk '{print $1}')
            echo "SHA256_BHF=$sha256" >> $GITHUB_ENV

      - name: Calculate SHA256 for BEEESSS_Paril_Hairstyle_Extended.zip
        id: sha256-BPHE
        run: |
            sha256=$(shasum -a 256 BEEESSS_Paril_Hairstyle_Extended.zip | awk '{print $1}')
            echo "SHA256_BPHE=$sha256" >> $GITHUB_ENV

      - name: Calculate SHA256 for BEEESSS_Wax.zip
        id: sha256-BW
        run: |
              sha256=$(shasum -a 256 BEEESSS_Wax.zip | awk '{print $1}')
              echo "SHA256_BW=$sha256" >> $GITHUB_ENV

      - name: Calculate SHA256 for Goose_Female.zip
        id: sha256-GF
        run: |
              sha256=$(shasum -a 256 Goose_Female.zip | awk '{print $1}')
              echo "SHA256_GF=$sha256" >> $GITHUB_ENV

      - name: Calculate SHA256 for Goose_Female_Mysterious.zip
        id: sha256-GFM
        run: |
              sha256=$(shasum -a 256 Goose_Female_Mysterious.zip | awk '{print $1}')
              echo "SHA256_GFM=$sha256" >> $GITHUB_ENV

      # 发布到Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
            tag_name: "release-${{ env.RELEASE_DATE }}"  # 使用生成的日期作为标签
            name: "Release ${{ env.RELEASE_DATE }}"      # Release标题名称
            draft: false
            prerelease: false
            body: |
                ${{ env.RELEASE_DATE }}
                ## File SHA256 Checksums
                - BEEESSS_Hikari_Female.zip: `${{ env.SHA256_BHF }}`
                - BEEESSS_Paril_Hairstyle_Extended.zip: `${{ env.SHA256_BPHE }}`
                - BEEESSS_Wax.zip: `${{ env.SHA256_BW }}`
                - Goose_Female.zip: `${{ env.SHA256_GF }}`
                - Goose_Female_Mysterious.zip: `${{ env.SHA256_GFM }}`
                ## Verify Your Download
                PowerShell: `certutil -hashfile [file] sha256`
                Linux Terminal: `shasum -a 256 [file]` 
            files: |
                BEEESSS_Hikari_Female.zip
                BEEESSS_Paril_Hairstyle_Extended.zip
                BEEESSS_Wax.zip
                Goose_Female.zip
                Goose_Female_Mysterious.zip
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
